default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %>
  timeout: 5000
  database: <%= ENV['PG_DATABASE'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
